### ISSUE TITLE
Refactor release pipeline to make it runnable regularly

### ISSUE THREAD

**Issue by zepatrik** [ory/ci#57]
The release process currently is only ever run on release, but between the releases many things change so we usually need multiple pre-releases to fix all the CI jobs before a release. Instead, the jobs should be regularly run/tested so that they always work.

**Comment by mohitsaxenaknoldus** [comment]
I'll work on this. Please assign it to me.

**Comment by aeneasr** [comment]
We can’t assign it but feel free to work on it :)

**Comment by mohitsaxenaknoldus** [comment]
@aeneasr @zepatrik If I am understanding this correctly then you want your CI checks to run on all releases right?

**Comment by zepatrik** [comment]
We have CI running on every release, but because we don't have releases every other day it usually is outdated and needs config adjustments once we properly release. We somehow have to check regularly that the release pipeline is still working as it should without making a release.

**Comment by mohitsaxenaknoldus** [comment]
One solution that comes to my mind instantly is making a mirror of this repo on GitLab and there we can keep running our tests? How does it sound to you guys? This way that other CI pipeline will keep informing us of the build statuses.

**Comment by aeneasr** [comment]
We do pre-releases now, which kind of resolves (works around) the issue.
